/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Blindbox: typeof import('./src/components/Blindbox.vue')['default']
    Custom: typeof import('./src/components/Custom.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    IEpArrowLeft: typeof import('~icons/ep/arrow-left')['default']
    IEpArrowRight: typeof import('~icons/ep/arrow-right')['default']
    IEpCircleCloseFilled: typeof import('~icons/ep/circle-close-filled')['default']
    Jiugongge: typeof import('./src/components/Jiugongge.vue')['default']
    OpenSpecialEffects: typeof import('./src/components/OpenSpecialEffects.vue')['default']
  }
}
