name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # 当创建新的版本标签时触发

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Build Vue.js app
        run: npm run build

      - name: Build Electron app
        run: npm run make

      - name: List output files
        run: ls -la out/make

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: out/make/*.zip

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-artifact
          path: out/make/*.zip

  attach-release:
    needs: build-and-release
    runs-on: macos-latest
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v2
        with:
          name: macos-artifact
          path: ./out/make/

      - name: Attach macOS artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ needs.build-and-release.outputs.upload_url }}
          asset_path: ./out/make/*.zip
          asset_name: your-app-name-macos.zip
          asset_content_type: application/zip
